# 异常
>* 捕获异常的结构：
>   ```
>   try:
>       pass  #可能出现异常的语句，逻辑语句
>   except 异常类型1  as error:  # except语句可以有多个
>       pass  #try语句出现异常后会自动跳转并执行except语句块
>   except 异常类型2 as error:
>       pass  #try语句出现异常后会自动跳转并执行except语句块
>   except 异常类型3 as error:
>       pass  #try语句出现异常后会自动跳转并执行except语句块
>   except Exception as error:
>       pass # 最顶层的异常，能捕获所有异常
>   else:
>       pass  # try语句块代码无异常且没有return会执行该语句块
>   finally:
>       pass  # 一定会执行的语句
>   ```
>* try语句块不能单独使用
>* except语句块：
>   * 用于拦截try语句块中的异常
>   * 通过```except Exception as error```将异常对象传递给error变量，可在except语句块中访问该异常对象
>   * 所有的异常都间接或直接基础于Exception异常，所以Exception可拦截所有异常，等级最高
>   * except语句块可以有多个，建议自上而下等级主键提高
>* 主动抛出异常(raise)：
>   * 结构：```raise 异常类型(提示信息)```
>   * 使用raise关键字主动抛出异常
>       ```
>       # 抛出异常
>       def func_name():
>           pass
>           if xxx:
>               raise 异常类型(提示信息)
>       # 处理异常
>       try:
>           pass
>           func_name()
>       except Exception as error
>           pass
>           print(error)
>       else:
>           pass
>           print('代码执行无异常')
>       finally:
>           pass
>       ```
>
